services:
  mysql:
    image: mysql:8.0
    container_name: medifinder-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medifinder-ai
      MYSQL_USER: medifinder
      MYSQL_PASSWORD: medifinder
    ports:
      - '3309:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: